const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const source = fs.readFileSync('Assets/js/news.js', 'utf8');
const start = source.indexOf('    function initializePostCardLinks(');
const end = source.indexOf('    /*', start);
let handler, opened = 0, selection = '';
const title = {textContent:'Test post', firstChild:null, appendChild(link){this.link=link;}};
const card = {dataset:{type:'announcement',contentId:'74'},querySelector(){return title;},classList:{add(){}},addEventListener(name,fn){handler=fn;}};
const context = vm.createContext({document:{createElement(){return {setAttribute(){},appendChild(){}};}},window:{getSelection(){return {toString(){return selection;}};}},postPageUrl(){return 'post';},openPostTab(type,id){assert.equal(type,'announcement');assert.equal(id,74);opened++;}});
vm.runInContext(source.slice(start,end),context);
context.initializePostCardLinks([card]);
const click = (interactive=false) => ({button:0,target:{closest(){return interactive;}}});
handler(click()); assert.equal(opened,1);
handler(click(true)); assert.equal(opened,1);
selection='selected text';handler(click());assert.equal(opened,1);
selection='';handler({...click(),defaultPrevented:true});assert.equal(opened,1);
assert.equal(title.link.target,'_blank');assert.equal(title.link.rel,'noopener noreferrer');
console.log('PASS: card opens post; controls, text selection, and canceled clicks do not.');
