CREATE TABLE `parent_child_record` (
  `parent_user_id` int(11) NOT NULL,
  `child_name` varchar(200) NOT NULL,
  `child_student_id` varchar(50) DEFAULT NULL,
  `section_id` int(11) NOT NULL,
  `relationship` varchar(50) NOT NULL,
  `reason` varchar(32) NOT NULL,
  `reason_details` varchar(500) NOT NULL DEFAULT '',
  `status` enum('Pending','Verified','Rejected','Revoked','Linked') NOT NULL DEFAULT 'Pending',
  `verified_by` int(11) DEFAULT NULL,
  `verified_at` datetime DEFAULT NULL,
  `review_notes` varchar(1000) DEFAULT NULL,
  `review_history` longtext DEFAULT NULL,
  `linked_student_user_id` int(11) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (`parent_user_id`),
  KEY `idx_child_record_student_id` (`child_student_id`),
  KEY `fk_child_record_section` (`section_id`),
  KEY `fk_child_record_verifier` (`verified_by`),
  KEY `fk_child_record_student` (`linked_student_user_id`),
  CONSTRAINT `fk_child_record_parent` FOREIGN KEY (`parent_user_id`) REFERENCES `user` (`user_id`),
  CONSTRAINT `fk_child_record_section` FOREIGN KEY (`section_id`) REFERENCES `section` (`section_id`),
  CONSTRAINT `fk_child_record_student` FOREIGN KEY (`linked_student_user_id`) REFERENCES `user` (`user_id`),
  CONSTRAINT `fk_child_record_verifier` FOREIGN KEY (`verified_by`) REFERENCES `user` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
